name: Run Linting
on: pull_request
jobs:
  Linting:
    name: run-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/hydrogen

      - name: Run CI
        run: npm ci

      - name: Run Lint Prettier
        run: npm run lint:prettier:fix

      - name: Run Lint ESLint
        run: "npm run lint:eslint:check"
