name: Run Tests
on: pull_request
jobs:
  Tests:
    name: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/hydrogen

      - name: Run CI
        run: npm ci

      - name: Run Test
        run: npm run test
