name: Run Tests
on: pull_request
Jobs:
  name:
    run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: setup/nodejs@v4
        with:
          node-version: lts/hydrogen

      - run: npm ci

      - run: npm run test
